### ISSUE TITLE
Use the "warnings" package?

### ISSUE THREAD

**Issue by olebole** [ACCarnall/SpectRes#3]
Hi,

the package currently implements its own way to handle warnings:

https://github.com/ACCarnall/SpectRes/blob/e10e9c53957becb3d95791e8731a335386cc93b3/spectres/spectral_resampling.py#L103-L107

Python itself ("batteries included") however comes with a standard way to handle warningswith [the `warnings` package](https://docs.python.org/3/library/warnings.html). Would you consider using this instead? This would make the package more consistent with other Python packages.

**Comment by WillJRoper** [comment]
This would also allow users to silence any warnings globally if they know what they are doing. We're using spectres in [Synthesizer](https://github.com/flaresimulations/synthesizer) and get these intrusive prints fairly often.

One solution for us would be to just call with the `verbose` flag set to `False` but that hides the warning entirely which isn't always wanted (e.g. it's fine to silence them if you know it's happening and are ok with it but to the uninitiated user it could lead to confusion having this hidden).

It's a very simple fix and will reduce your logic by removing the `warned` flag too.

**Comment by ACCarnall** [comment]
Hi Will,

If you fancy drafting a pull request I'd be happy to accept it and distribute a new version via pip.

Cheers,
Adam

**Comment by WillJRoper** [comment]
Done (I may have set about this before seeing your response to my comment 😅).
