### ISSUE TITLE
numba compiled version

### ISSUE THREAD

**Issue by RhysSeeburger** [ACCarnall/SpectRes#7]
Hey! In docs you mention that there is now a numba complied version (https://spectres.readthedocs.io/en/latest/)

However, when I pip install and dir(spectres), there is only the spectres and spectral_resampling modules; no spectres_numba. Is the PyPi version outdated?

Thanks!

**Comment by ACCarnall** [comment]
Nope, the version on pypi is up to date. Do you have numba installed? The code won't load up the spectres_numba module if numba isn't installed.

**Comment by RhysSeeburger** [comment]
I did not in the environment I was using - it works now, thanks!
